# Generated by Django 4.2.4 on 2024-01-07 15:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotofacil',
            name='qntNumerosPorJogo',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(25)]),
        ),
    ]
