# Generated by Django 4.2.4 on 2024-01-08 23:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_lotofacil_qntnumerosporjogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotofacil',
            name='qntNumerosPorJogo',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
