# Generated by Django 4.2.4 on 2024-01-09 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_lotofacil_qntnumerosporjogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotofacil',
            name='qntJogos',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lotofacil',
            name='qntNumerosPorJogo',
            field=models.IntegerField(),
        ),
    ]
