# Generated by Django 4.2.4 on 2024-01-09 22:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_lotofacil_qntnumerosporjogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotofacil',
            name='qntNumerosPorJogo',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(15, message='A quantidade deve ser um número de 15 a 20'), django.core.validators.MaxValueValidator(20, message='A quantidade deve ser um número de 15 a 20')]),
        ),
    ]
