# Generated by Django 4.2.4 on 2024-01-09 22:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_alter_lotofacil_qntjogos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotofacil',
            name='qntJogos',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='A quantidade de jogos deve ser um número igual ou maior que 1')]),
        ),
        migrations.AlterField(
            model_name='lotofacil',
            name='qntNumerosPorJogo',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(15, message='A quantidade de números por jogo deve ser um número de 15 a 20'), django.core.validators.MaxValueValidator(20, message='A quantidade de números por jogo deve ser um número de 15 a 20')]),
        ),
    ]
