# Generated by Django 4.2.4 on 2024-01-09 22:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_alter_lotofacil_qntjogos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MegaSena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qntJogos', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='A quantidade de jogos deve ser um número igual ou maior que 1')])),
                ('qntNumerosPorJogo', models.IntegerField(validators=[django.core.validators.MinValueValidator(6, message='A quantidade de números por jogo deve ser um número de 6 a 20'), django.core.validators.MaxValueValidator(20, message='A quantidade de números por jogo deve ser um número de 6 a 20')])),
            ],
        ),
    ]
